"""initial schema

Revision ID: 4c33278658de
Revises:
Create Date: 2026-09-29 08:38:36.295259+03:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "4c33278658de"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carriers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("inn", sa.String(length=12), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_carriers")),
    )
    op.create_index(op.f("ix_carriers_name"), "carriers", ["name"], unique=False)

    op.create_table(
        "stages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("is_closed", sa.Boolean(), nullable=False),
        sa.Column("color", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stages")),
    )
    op.create_index(op.f("ix_stages_sequence"), "stages", ["sequence"], unique=False)

    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("color", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("name", name=op.f("uq_tags_name")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "manager", "operator", name="role", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)

    op.create_table(
        "leads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("inn", sa.String(length=12), nullable=False),
        sa.Column("kpp", sa.String(length=9), nullable=False),
        sa.Column("timezone", sa.String(length=16), nullable=False),
        sa.Column("company_email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("logist_contact", sa.String(length=255), nullable=False),
        sa.Column("logist_phone", sa.String(length=32), nullable=False),
        sa.Column("logist_email", sa.String(length=255), nullable=True),
        sa.Column("credit_limit", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("first_call_date", sa.Date(), nullable=True),
        sa.Column("next_call_date", sa.Date(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("stage_id", sa.Integer(), nullable=False),
        sa.Column("assigned_to_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint("length(inn) IN (10, 12)", name=op.f("ck_leads_inn_length")),
        sa.CheckConstraint("priority BETWEEN 0 AND 3", name=op.f("ck_leads_priority_range")),
        sa.ForeignKeyConstraint(
            ["assigned_to_id"],
            ["users.id"],
            name=op.f("fk_leads_assigned_to_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"], ["stages.id"], name=op.f("fk_leads_stage_id_stages"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leads")),
    )
    op.create_index(op.f("ix_leads_assigned_to_id"), "leads", ["assigned_to_id"], unique=False)
    op.create_index(op.f("ix_leads_inn"), "leads", ["inn"], unique=False)
    op.create_index(op.f("ix_leads_is_archived"), "leads", ["is_archived"], unique=False)
    op.create_index(op.f("ix_leads_name"), "leads", ["name"], unique=False)
    op.create_index(op.f("ix_leads_stage_id"), "leads", ["stage_id"], unique=False)

    op.create_table(
        "lead_tags",
        sa.Column("lead_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_lead_tags_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_lead_tags_tag_id_tags"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("lead_id", "tag_id", name=op.f("pk_lead_tags")),
    )
    op.create_table(
        "shipments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lead_id", sa.Integer(), nullable=False),
        sa.Column("carrier_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "in_progress",
                "in_transit",
                "delivered",
                "cancelled",
                name="shipmentstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "transport_type",
            sa.Enum(
                "ft_20",
                "ft_40",
                "ref",
                "tent",
                "gazel",
                "other",
                name="transporttype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("city_loading", sa.String(length=120), nullable=False),
        sa.Column("city_unloading", sa.String(length=120), nullable=False),
        sa.Column("address_loading", sa.String(length=255), nullable=False),
        sa.Column("address_unloading", sa.String(length=255), nullable=False),
        sa.Column("contact_loading_name", sa.String(length=255), nullable=False),
        sa.Column("contact_loading_phone", sa.String(length=32), nullable=False),
        sa.Column("contact_unloading_name", sa.String(length=255), nullable=False),
        sa.Column("contact_unloading_phone", sa.String(length=32), nullable=False),
        sa.Column("cargo_weight", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("cargo_volume", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["carrier_id"],
            ["carriers.id"],
            name=op.f("fk_shipments_carrier_id_carriers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_shipments_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipments")),
    )
    op.create_index(op.f("ix_shipments_carrier_id"), "shipments", ["carrier_id"], unique=False)
    op.create_index(op.f("ix_shipments_lead_id"), "shipments", ["lead_id"], unique=False)
    op.create_index(op.f("ix_shipments_status"), "shipments", ["status"], unique=False)

    op.create_table(
        "timeline_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lead_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "note",
                "history",
                "message",
                "activity",
                name="entrytype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("field_label", sa.String(length=120), nullable=True),
        sa.Column("old_value", sa.String(length=255), nullable=True),
        sa.Column("new_value", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_timeline_entries_author_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
            name=op.f("fk_timeline_entries_lead_id_leads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_timeline_entries")),
    )
    op.create_index(
        op.f("ix_timeline_entries_lead_id"), "timeline_entries", ["lead_id"], unique=False
    )

    op.create_table(
        "attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lead_id", sa.Integer(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=True),
        sa.Column("uploaded_by_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=False),
        sa.Column("storage_path", sa.String(length=512), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["timeline_entries.id"],
            name=op.f("fk_attachments_entry_id_timeline_entries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_attachments_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["users.id"],
            name=op.f("fk_attachments_uploaded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
    )
    op.create_index(op.f("ix_attachments_entry_id"), "attachments", ["entry_id"], unique=False)
    op.create_index(op.f("ix_attachments_lead_id"), "attachments", ["lead_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_attachments_lead_id"), table_name="attachments")
    op.drop_index(op.f("ix_attachments_entry_id"), table_name="attachments")

    op.drop_table("attachments")
    op.drop_index(op.f("ix_timeline_entries_lead_id"), table_name="timeline_entries")

    op.drop_table("timeline_entries")
    op.drop_index(op.f("ix_shipments_status"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_lead_id"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_carrier_id"), table_name="shipments")

    op.drop_table("shipments")
    op.drop_table("lead_tags")
    op.drop_index(op.f("ix_leads_stage_id"), table_name="leads")
    op.drop_index(op.f("ix_leads_name"), table_name="leads")
    op.drop_index(op.f("ix_leads_is_archived"), table_name="leads")
    op.drop_index(op.f("ix_leads_inn"), table_name="leads")
    op.drop_index(op.f("ix_leads_assigned_to_id"), table_name="leads")

    op.drop_table("leads")
    op.drop_index(op.f("ix_users_email"), table_name="users")

    op.drop_table("users")
    op.drop_table("tags")
    op.drop_index(op.f("ix_stages_sequence"), table_name="stages")

    op.drop_table("stages")
    op.drop_index(op.f("ix_carriers_name"), table_name="carriers")

    op.drop_table("carriers")
    # ### end Alembic commands ###
