"""activities

Revision ID: 5c2628794daf
Revises: f9daa025e939
Create Date: 2026-09-29 11:09:56.343781+03:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "5c2628794daf"
down_revision: str | None = "f9daa025e939"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lead_id", sa.Integer(), nullable=False),
        sa.Column("assigned_to_id", sa.Integer(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "call",
                "meeting",
                "todo",
                "email",
                name="activitytype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.String(length=255), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("is_done", sa.Boolean(), nullable=False),
        sa.Column("done_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to_id"],
            ["users.id"],
            name=op.f("fk_activities_assigned_to_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_activities_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activities")),
    )
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_activities_assigned_to_id"), ["assigned_to_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_activities_due_date"), ["due_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_activities_is_done"), ["is_done"], unique=False)
        batch_op.create_index(batch_op.f("ix_activities_lead_id"), ["lead_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activities_lead_id"))
        batch_op.drop_index(batch_op.f("ix_activities_is_done"))
        batch_op.drop_index(batch_op.f("ix_activities_due_date"))
        batch_op.drop_index(batch_op.f("ix_activities_assigned_to_id"))

    op.drop_table("activities")
    # ### end Alembic commands ###
